In [ ]:
str = 'HackerRank.com presents "Pythonist 2".'
print()

In [2]:
def print_full_name(a, b):
    print("Hello " + a +" " + b + "!"+ " You just delved into python.")

In [3]:
if __name__ == '__main__':
    first_name = input()
    last_name = input()
    print_full_name(first_name, last_name)

Jyothi
Kunaparaju
Hello Jyothi Kunaparaju! You just delved into python.


In [ ]:
string.count(sub_string)

In [30]:
def find_all(a_str, sub):
    start = 0
    
    while True:
        start = a_str.find(sub, start)
        print(start)
        if start == -1: return
        yield start
        start += 1
        # len(sub) # use start += 1 to find overlapping matches

#len(list(find_all('ABCDCDC', 'CDC'))) # [0, 5, 10, 15]

In [40]:
 print(any(map(str.isalnum,'qA2')))

True


In [50]:
x = (hex(17))
print(x)

0x11


In [51]:
print(int(x , 16))

17


In [53]:
st =17

In [60]:
w=len(bin(st)[2:])
w

5

In [64]:
str(oct(st)[2:]).rjust(w,' ')

'   21'

In [63]:
bin(17)[2:]

'10001'

In [78]:
st=int(input())
w=len(bin(st)[2:])
for i in range(1,st+1):
    print (str(st).rjust(w,' '),str(oct(st)[2:]).rjust(w,' '),str(hex(st)[2:].upper()).rjust(w,' '),str(bin(st)[2:]).rjust(w,' '),sep=' ')

17
   17    21    11 10001
   17    21    11 10001
   17    21    11 10001
   17    21    11 10001
   17    21    11 10001
   17    21    11 10001
   17    21    11 10001
   17    21    11 10001
   17    21    11 10001
   17    21    11 10001
   17    21    11 10001
   17    21    11 10001
   17    21    11 10001
   17    21    11 10001
   17    21    11 10001
   17    21    11 10001
   17    21    11 10001


In [79]:
def print_formatted(number):
    # your code goes here 
    w=len(bin(number)[2:])
    for i in range(1,number+1):
        print (str(i).rjust(w,' '),str(oct(i)[2:]).rjust(w,' '),str(hex(i)[2:].upper()).rjust(w,' '),str(bin(i)[2:]).rjust(w,' '),sep=' ')

In [81]:
n = int(input())
print_formatted(n)

2
 1  1  1  1
 2  2  2 10


In [1]:
import string
alpha = string.ascii_lowercase

n = int(input())
L = []
for i in range(n):
    s = "-".join(alpha[i:n])    
    L.append((s[::-1]+s[1:]).center(4*n-3, "-"))
print('\n'.join(L[:0:-1]+L))

3
----c----
--c-b-c--
c-b-a-b-c
--c-b-c--
----c----


In [2]:
def print_rangoli(size):
    # your code goes here
    alpha = string.ascii_lowercase
    L = []
    for i in range(size):
        s = "-".join(alpha[i:size])    
        L.append((s[::-1]+s[1:]).center(4*size-3, "-"))
        
    print('\n'.join(L[:0:-1]+L))

In [4]:
n = int(input())
print_rangoli(n)

5
--------e--------
------e-d-e------
----e-d-c-d-e----
--e-d-c-b-c-d-e--
e-d-c-b-a-b-c-d-e
--e-d-c-b-c-d-e--
----e-d-c-d-e----
------e-d-e------
--------e--------


In [4]:
import string
def cap(st):
    return string.capwords(st)


In [7]:
st = "john's    school"
capitalized_string = cap(st)
print(capitalized_string)

John's School


In [8]:
st = "john's  doe   school"
def capitalize(string):
    l=string.split(" ")
    a = [i.capitalize() for i in l]       
    return " ".join(a)

In [9]:
print(capitalize(st))

John's  Doe   School


In [7]:
def average(array):
    # your code goes here
    s = set(array)
    print(s)
    return sum(s)/len(s)


In [8]:
str ='12  12 13 14 15'
arr = list(map(int, str.split()))

len(arr)

5

In [6]:
s = set(arr)
len(s)

4

In [9]:
result = average(arr)
print(result)

{12, 13, 14, 15}
13.5


In [12]:
a = {2, 9, 5, 4}
b = {2, 4, 11, 12}
c = a.intersection(b)
d= a.union(b)
ans = d.difference(c)

In [13]:
ans


{5, 9, 11, 12}

In [ ]:
M = input()
arr1 = list(map(int, input().split()))
a=set(arr1)
N= input()
arr2 = list(map(int, input().split()))
b= set(arr2)
c = a.intersection(b)
d= a.union(b)
ans = set ( d.difference(c))


In [21]:
ans


{1, 2, 3, 4, 5, 7, 8, 9}

In [2]:

m ="2 4 5 9"
arr1 = list(map(int, m.split()))
a=set(arr1)


In [5]:
arr2 = list(map(int, '2 4 11 12'.split()))
b= set(arr2)
c = a.intersection(b)
d= a.union(b)
ans = sorted(set ( d.difference(c)))
for i in ans :
    print(i)

5
9
11
12


In [10]:
n, m = input().split()

sc_ar = input().split()
A = set(input().split())
B = set(input().split())
def like ( a , b , sc_sr ):
    sc = 0 
    for i  in sc_ar  :  
        if(i in a )  : sc = sc + 1 
        if(i in b )  : sc = sc - 1
    return sc
print(like(A, B , sc_ar))
#print sum([(i in A) - (i in B)
          # for i in sc_ar])

3 2 
1 4 6 7 8 9 
1 6  7  8  9 
6 7 8 2 3 
2


In [14]:
s = set('HackerRank')
#print s.add('HackerRank')
st = [ 'UK' , 'China' ,'USA' , 'France' ,'New Zealand' ,'UK' ,'France']
set_st = set(st)

In [21]:
st = input()
print(st)
list_st = [st]
set_st = set(list_st)
print(set_st)

UK China USA France New Zealand UK France
UK China USA France New Zealand UK France
{'UK China USA France New Zealand UK France'}


In [16]:
print(len(set_st))

5


In [30]:
num = input()
st = set()
for i in range(int(num)) :
    st.add(input())
print(len(st))


5
UK
Chine
Chine
France
France
3


9
1 2 3 4 5 6 7 8 9
10
pop
remove 9
discard 9
discard 8
remove 7
pop 
discard 6
remove 5
pop 
discard 5

In [7]:
num = input()
sc_ar = input().split()
sc_set = set(sc_ar)
num_com = input()
for i in range(int(num_com)) :
    in_put = input().split()
    in_com = in_put[0]
    print(len(in_put))
    str_st=''
    if len(in_put) == 2  :     
        in_param = in_put[1]
        str_st = 'sc_set'+'.'+ in_com + '(' + in_param + ')'
    else :  
        str_st = 'sc_set'+'.'+ in_com + '()'   
    eval(str_st)
    
    

9
1 2 3 4 5 6 7 8 9
3
remove 9
2


KeyError: 9

In [26]:
year = int(input())
leap = False
if( (year%400 == 0) or  all ([year %100 !=0 ,  year%4 == 0 ])) :  leap = True 
print(leap)

1998
False


In [48]:
from __future__ import print_function
n = int(input())
l = list(range(1,n+1))
for item in l :
    print(item, sep=' ', end='', flush=True)
      
#for i in range(n) :
#    print(i)


20
1234567891011121314151617181920

In [66]:
n = int(input())
set_s = set(map(int, input().split())) 
for i in range(int(input())):
    ft = list(input().split())
    eval('set_s.{0}({1})'.format(*ft +[''] ))

print(sum(set_s))

9
1 2 3 4 5 6 7 8 9
3
pop
pop
pop
39


In [ ]:
pop
remove 9
discard 9
discard 8
remove 7
pop
discard 6
remove 5
pop
discard 5

In [74]:
n = int(input())
s = set(map(int, input().split())) 

for _ in range(int(input())):
    args = input().strip().split()
    
    if args[0] == "pop": 
        s.pop()
    else:
        eval("s." + args[0] + "(" + args[1] + ")")
        
print(sum(s))  
#pop
#remove 9
#discard 9
#discard 8
#remove 7 pop discard 6 remove 5 pop discard 5

9
1 2 3 4 5 6 7 8 9
3
pop
remove 9
discard 9
35


In [78]:
n = input()
s = set(map(int, input().split())) 

for _ in range(int(input())):
    x = list(input().split())
    eval('s.{0}({1})'.format(*x+['']))
print (sum(s))

9
1 2 3 4 5 6 7 8 9
3
pop
remove 9
discard 9
35


In [4]:
li1 = input().split()
s1 = set(li1)
li2 = input().split()
s2 = set(li2)
s1s2 = s1.union(s2)
print(len(s1s2))

1 2 3 4 5 6 7 8 9
6 7 10 13 15 
12


In [5]:
n1=input()
li1 = input().split()
s1 = set(li1)
n2=input()
li2 = input().split()
s2 = set(li2)
s1s2 = s1.intersection(s2)
print(len(s1s2))

1 2 3 4 5 6 7 8 9
6 7 10 13 15 
2


In [8]:
n1=input()
li1 = input().split()
s1 = set(li1)
n2=input()
li2 = input().split()
s2 = set(li2)
s1s2 = s1.symmetric_difference(s2)
print(len(s1s2))

9
1 2 3 4 5 6 7 8 9
5
6 7 10 13 15
10


In [9]:
n = input()
s = set(map(int, input().split())) 

for _ in range(int(input())):
    x = list(input().split())
    nw= set(map(int, input().split())) 
    fi = eval('s.{0}(nw)'.format(*x+['']))
print(fi)

16
1 2 3 4 5 6 7 8 9 10 11 12 13 14 24 52
4
intersection_update 10
2 3 5 6 8 9 1 4 7 11
update 2
55 66
symmetric_difference_update 5
22 7 35 62 58
difference_update 7
11 22 35 55 58 62 66
None


In [3]:
n = input()
s = set(map(int, input().split())) 

for _ in range(int(input())):
    args = input().strip().split()
    nw= set(map(int, input().split())) 
    eval("s." + args[0] + "(  nw  )")
print(sum(s))


16
1 2 3 4 5 6 7 8 9 10 11 12 13 14 24 52
4
intersection_update 10
2 3 5 6 8 9 1 4 7 11
update 2
55 66
symmetric_difference_update 5
22 7 35 62 58
difference_update 7
11 22 35 55 58 62 66
{1, 2, 3, 4, 5, 6, 8, 9}


In [20]:
import collections
n = input()
s = list(map(int, input().split())) 
lis = sorted(s)
counter=collections.Counter(lis)
d = dict(counter)
print( [k for k, v in d.items() if v == 1][0])
    

5
1 2 3 6 5 4 4 2 5 3 6 1 6 5 3 2 4 1 2 5 1 4 3 6 8 4 3 1 5 6 
8


In [42]:
l = []
for i in range(int(input())):
    n1 ,  set1  , n2 , set2= input(), set(map(int, input().split())),input() ,set(map(int, input().split()))   
    l.append((set1 < set2))
for i in  l : print (i)

2
3
1 2 3
9
1 3 5 6 8 9 0 9 8
2
1 2 
3
1 4 5 
False
False


In [ ]:
1 2 3 5 6
9



In [2]:
mainset = set(map(int, input().split()))
superset = True
for _ in range(int(input())):
    subset = set(map(int, input().split()))
    superset =  mainset.issuperset(subset)
    if(not superset): break
print(superset)

1 2 3 4 5 6 7 8 9 10 11 12 23 45 84 7
3 
2  3 
4 5 
34
False


In [4]:
import numpy
n, m = map(int, input().split())
array = numpy.array([input().strip().split() for _ in range(n)], int)
print (array.transpose())
print (array.flatten())

2 3 
1 2 3 
2 3 4 
[[1 2]
 [2 3]
 [3 4]]
[1 2 3 2 3 4]


In [6]:
array = numpy.array([[1, 2, 3 ],[2 ,3 ,4]])

In [7]:
array
np.concatenate((a, b))

array([[1, 2, 3],
       [2, 3, 4]])

In [12]:
import numpy
n, m = map(int, input().split())
arr = numpy.zeros(shape=(n,m))
for i in range(n):
    arr[i] = list(map(int, input().split()))
arr = arr.astype(int)
print (arr.transpose())
print (arr.flatten())

2 2 
2 5 
2 6
[[2 2]
 [5 6]]
[2 5 2 6]
