In [1]:
str = 'HackerRank.com presents "Pythonist 2".'
print()

In [2]:
def print_full_name(a, b):
    print("Hello " + a +" " + b + "!"+ " You just delved into python.")

In [3]:
if __name__ == '__main__':
    first_name = input()
    last_name = input()
    print_full_name(first_name, last_name)

Jyothi
Kunaparaju
Hello Jyothi Kunaparaju! You just delved into python.


In [ ]:
string.count(sub_string)

In [30]:
def find_all(a_str, sub):
    start = 0
    
    while True:
        start = a_str.find(sub, start)
        print(start)
        if start == -1: return
        yield start
        start += 1
        # len(sub) # use start += 1 to find overlapping matches

#len(list(find_all('ABCDCDC', 'CDC'))) # [0, 5, 10, 15]

In [40]:
 print(any(map(str.isalnum,'qA2')))

True


In [50]:
x = (hex(17))
print(x)

0x11


In [51]:
print(int(x , 16))

17


In [53]:
st =17

In [60]:
w=len(bin(st)[2:])
w

5

In [64]:
str(oct(st)[2:]).rjust(w,' ')

'   21'

In [63]:
bin(17)[2:]

'10001'

In [78]:
st=int(input())
w=len(bin(st)[2:])
for i in range(1,st+1):
    print (str(st).rjust(w,' '),str(oct(st)[2:]).rjust(w,' '),str(hex(st)[2:].upper()).rjust(w,' '),str(bin(st)[2:]).rjust(w,' '),sep=' ')

17
   17    21    11 10001
   17    21    11 10001
   17    21    11 10001
   17    21    11 10001
   17    21    11 10001
   17    21    11 10001
   17    21    11 10001
   17    21    11 10001
   17    21    11 10001
   17    21    11 10001
   17    21    11 10001
   17    21    11 10001
   17    21    11 10001
   17    21    11 10001
   17    21    11 10001
   17    21    11 10001
   17    21    11 10001


In [79]:
def print_formatted(number):
    # your code goes here 
    w=len(bin(number)[2:])
    for i in range(1,number+1):
        print (str(i).rjust(w,' '),str(oct(i)[2:]).rjust(w,' '),str(hex(i)[2:].upper()).rjust(w,' '),str(bin(i)[2:]).rjust(w,' '),sep=' ')

In [81]:
n = int(input())
print_formatted(n)

2
 1  1  1  1
 2  2  2 10


In [1]:
import string
alpha = string.ascii_lowercase

n = int(input())
L = []
for i in range(n):
    s = "-".join(alpha[i:n])    
    L.append((s[::-1]+s[1:]).center(4*n-3, "-"))
print('\n'.join(L[:0:-1]+L))

3
----c----
--c-b-c--
c-b-a-b-c
--c-b-c--
----c----


In [2]:
def print_rangoli(size):
    # your code goes here
    alpha = string.ascii_lowercase
    L = []
    for i in range(size):
        s = "-".join(alpha[i:size])    
        L.append((s[::-1]+s[1:]).center(4*size-3, "-"))
        
    print('\n'.join(L[:0:-1]+L))

In [4]:
n = int(input())
print_rangoli(n)

5
--------e--------
------e-d-e------
----e-d-c-d-e----
--e-d-c-b-c-d-e--
e-d-c-b-a-b-c-d-e
--e-d-c-b-c-d-e--
----e-d-c-d-e----
------e-d-e------
--------e--------


In [4]:
import string
def cap(st):
    return string.capwords(st)


In [7]:
st = "john's    school"
capitalized_string = cap(st)
print(capitalized_string)

John's School


In [8]:
st = "john's  doe   school"
def capitalize(string):
    l=string.split(" ")
    a = [i.capitalize() for i in l]       
    return " ".join(a)

In [9]:
print(capitalize(st))

John's  Doe   School


In [7]:
def average(array):
    # your code goes here
    s = set(array)
    print(s)
    return sum(s)/len(s)


In [8]:
str ='12  12 13 14 15'
arr = list(map(int, str.split()))

len(arr)

5

In [6]:
s = set(arr)
len(s)

4

In [9]:
result = average(arr)
print(result)

{12, 13, 14, 15}
13.5


In [12]:
a = {2, 9, 5, 4}
b = {2, 4, 11, 12}
c = a.intersection(b)
d= a.union(b)
ans = d.difference(c)

In [13]:
ans


{5, 9, 11, 12}

In [ ]:
M = input()
arr1 = list(map(int, input().split()))
a=set(arr1)
N= input()
arr2 = list(map(int, input().split()))
b= set(arr2)
c = a.intersection(b)
d= a.union(b)
ans = set ( d.difference(c))


In [21]:
ans


{1, 2, 3, 4, 5, 7, 8, 9}

In [2]:

m ="2 4 5 9"
arr1 = list(map(int, m.split()))
a=set(arr1)


In [5]:
arr2 = list(map(int, '2 4 11 12'.split()))
b= set(arr2)
c = a.intersection(b)
d= a.union(b)
ans = sorted(set ( d.difference(c)))
for i in ans :
    print(i)

5
9
11
12


In [10]:
n, m = input().split()

sc_ar = input().split()
A = set(input().split())
B = set(input().split())
def like ( a , b , sc_sr ):
    sc = 0 
    for i  in sc_ar  :  
        if(i in a )  : sc = sc + 1 
        if(i in b )  : sc = sc - 1
    return sc
print(like(A, B , sc_ar))
#print sum([(i in A) - (i in B)
          # for i in sc_ar])

3 2 
1 4 6 7 8 9 
1 6  7  8  9 
6 7 8 2 3 
2


In [14]:
s = set('HackerRank')
#print s.add('HackerRank')
st = [ 'UK' , 'China' ,'USA' , 'France' ,'New Zealand' ,'UK' ,'France']
set_st = set(st)

In [21]:
st = input()
print(st)
list_st = [st]
set_st = set(list_st)
print(set_st)

UK China USA France New Zealand UK France
UK China USA France New Zealand UK France
{'UK China USA France New Zealand UK France'}


In [16]:
print(len(set_st))

5


In [30]:
num = input()
st = set()
for i in range(int(num)) :
    st.add(input())
print(len(st))


5
UK
Chine
Chine
France
France
3


9
1 2 3 4 5 6 7 8 9
10
pop
remove 9
discard 9
discard 8
remove 7
pop 
discard 6
remove 5
pop 
discard 5

In [7]:
num = input()
sc_ar = input().split()
sc_set = set(sc_ar)
num_com = input()
for i in range(int(num_com)) :
    in_put = input().split()
    in_com = in_put[0]
    print(len(in_put))
    str_st=''
    if len(in_put) == 2  :     
        in_param = in_put[1]
        str_st = 'sc_set'+'.'+ in_com + '(' + in_param + ')'
    else :  
        str_st = 'sc_set'+'.'+ in_com + '()'   
    eval(str_st)
    
    

9
1 2 3 4 5 6 7 8 9
3
remove 9
2


KeyError: 9

In [26]:
year = int(input())
leap = False
if( (year%400 == 0) or  all ([year %100 !=0 ,  year%4 == 0 ])) :  leap = True 
print(leap)

1998
False


In [48]:
from __future__ import print_function
n = int(input())
l = list(range(1,n+1))
for item in l :
    print(item, sep=' ', end='', flush=True)
      
#for i in range(n) :
#    print(i)


20
1234567891011121314151617181920

In [66]:
n = int(input())
set_s = set(map(int, input().split())) 
for i in range(int(input())):
    ft = list(input().split())
    eval('set_s.{0}({1})'.format(*ft +[''] ))

print(sum(set_s))

9
1 2 3 4 5 6 7 8 9
3
pop
pop
pop
39


In [ ]:
pop
remove 9
discard 9
discard 8
remove 7
pop
discard 6
remove 5
pop
discard 5

In [74]:
n = int(input())
s = set(map(int, input().split())) 

for _ in range(int(input())):
    args = input().strip().split()
    
    if args[0] == "pop": 
        s.pop()
    else:
        eval("s." + args[0] + "(" + args[1] + ")")
        
print(sum(s))  
#pop
#remove 9
#discard 9
#discard 8
#remove 7 pop discard 6 remove 5 pop discard 5

9
1 2 3 4 5 6 7 8 9
3
pop
remove 9
discard 9
35


In [78]:
n = input()
s = set(map(int, input().split())) 

for _ in range(int(input())):
    x = list(input().split())
    eval('s.{0}({1})'.format(*x+['']))
print (sum(s))

9
1 2 3 4 5 6 7 8 9
3
pop
remove 9
discard 9
35


In [4]:
li1 = input().split()
s1 = set(li1)
li2 = input().split()
s2 = set(li2)
s1s2 = s1.union(s2)
print(len(s1s2))

1 2 3 4 5 6 7 8 9
6 7 10 13 15 
12


In [5]:
n1=input()
li1 = input().split()
s1 = set(li1)
n2=input()
li2 = input().split()
s2 = set(li2)
s1s2 = s1.intersection(s2)
print(len(s1s2))

1 2 3 4 5 6 7 8 9
6 7 10 13 15 
2


In [8]:
n1=input()
li1 = input().split()
s1 = set(li1)
n2=input()
li2 = input().split()
s2 = set(li2)
s1s2 = s1.symmetric_difference(s2)
print(len(s1s2))

9
1 2 3 4 5 6 7 8 9
5
6 7 10 13 15
10


In [9]:
n = input()
s = set(map(int, input().split())) 

for _ in range(int(input())):
    x = list(input().split())
    nw= set(map(int, input().split())) 
    fi = eval('s.{0}(nw)'.format(*x+['']))
print(fi)

16
1 2 3 4 5 6 7 8 9 10 11 12 13 14 24 52
4
intersection_update 10
2 3 5 6 8 9 1 4 7 11
update 2
55 66
symmetric_difference_update 5
22 7 35 62 58
difference_update 7
11 22 35 55 58 62 66
None


In [3]:
n = input()
s = set(map(int, input().split())) 

for _ in range(int(input())):
    args = input().strip().split()
    nw= set(map(int, input().split())) 
    eval("s." + args[0] + "(  nw  )")
print(sum(s))


16
1 2 3 4 5 6 7 8 9 10 11 12 13 14 24 52
4
intersection_update 10
2 3 5 6 8 9 1 4 7 11
update 2
55 66
symmetric_difference_update 5
22 7 35 62 58
difference_update 7
11 22 35 55 58 62 66
{1, 2, 3, 4, 5, 6, 8, 9}


In [20]:
import collections
n = input()
s = list(map(int, input().split())) 
lis = sorted(s)
counter=collections.Counter(lis)
d = dict(counter)
print( [k for k, v in d.items() if v == 1][0])
    

5
1 2 3 6 5 4 4 2 5 3 6 1 6 5 3 2 4 1 2 5 1 4 3 6 8 4 3 1 5 6 
8


In [42]:
l = []
for i in range(int(input())):
    n1 ,  set1  , n2 , set2= input(), set(map(int, input().split())),input() ,set(map(int, input().split()))   
    l.append((set1 < set2))
for i in  l : print (i)

2
3
1 2 3
9
1 3 5 6 8 9 0 9 8
2
1 2 
3
1 4 5 
False
False


In [ ]:
1 2 3 5 6
9



In [2]:
mainset = set(map(int, input().split()))
superset = True
for _ in range(int(input())):
    subset = set(map(int, input().split()))
    superset =  mainset.issuperset(subset)
    if(not superset): break
print(superset)

1 2 3 4 5 6 7 8 9 10 11 12 23 45 84 7
3 
2  3 
4 5 
34
False


In [4]:
import numpy
n, m = map(int, input().split())
array = numpy.array([input().strip().split() for _ in range(n)], int)
print (array.transpose())
print (array.flatten())

2 3 
1 2 3 
2 3 4 
[[1 2]
 [2 3]
 [3 4]]
[1 2 3 2 3 4]


In [6]:
array = numpy.array([[1, 2, 3 ],[2 ,3 ,4]])

In [7]:
array
np.concatenate((a, b))

array([[1, 2, 3],
       [2, 3, 4]])

In [12]:
import numpy
n, m = map(int, input().split())
arr = numpy.zeros(shape=(n,m))
for i in range(n):
    arr[i] = list(map(int, input().split()))
arr = arr.astype(int)
print (arr.transpose())
print (arr.flatten())

2 2 
2 5 
2 6
[[2 2]
 [5 6]]
[2 5 2 6]


### Concatenate (Dashboard  Python  Numpy  Concatenate)

In [29]:
import numpy
N , M , P = map(int , input().strip().split(' '))
array_N  = numpy.zeros(shape=(N,P))
for i in range(N):
    array_N[i] = list(map(int,input().strip().split()))
array_M =  numpy.zeros(shape=(M,P))
for i in range(M):
    array_M[i]= list(map(int,input().strip().split()))
array_M = array_M.astype(int)
array_N = array_N.astype(int)
#print(array_N)
#print(array_M)
print (numpy.concatenate((array_N, array_M), axis = 0))   

#print(array_M)



4 3 2
1 2
1 2
1 2
1 2
2 3
2 3
2 3
[[1 2]
 [1 2]
 [1 2]
 [1 2]]
[[2 3]
 [2 3]
 [2 3]]
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [2 3]
 [2 3]
 [2 3]]


### Zeros and Ones

In [38]:
import numpy
in_list = list(map(int , input().strip().split(' ')))
if(len(in_list) == 3 )  :
    array_N  = numpy.zeros(shape=(in_list[0], in_list[1] , in_list[2]))
    array_M  = numpy.ones(shape=(in_list[0], in_list[1] , in_list[2]))
elif (len(in_list) == 2 )  :
    array_N  = numpy.zeros(shape=(in_list[0], in_list[1] ))
    array_M  = numpy.ones(shape=(in_list[0], in_list[1] ))
else   :
    array_N  = numpy.zeros(shape=(in_list[0] ))
    array_M  = numpy.ones(shape=(in_list[0] ))
    
array_N = array_N.astype(int)
array_M = array_M.astype(int)
print(array_N)
print(array_M)

3
[0 0 0]
[1 1 1]


In [44]:
print( numpy.zeros(shape= (3,2,3,4)))

[[[[ 0.  0.  0.  0.]
   [ 0.  0.  0.  0.]
   [ 0.  0.  0.  0.]]

  [[ 0.  0.  0.  0.]
   [ 0.  0.  0.  0.]
   [ 0.  0.  0.  0.]]]


 [[[ 0.  0.  0.  0.]
   [ 0.  0.  0.  0.]
   [ 0.  0.  0.  0.]]

  [[ 0.  0.  0.  0.]
   [ 0.  0.  0.  0.]
   [ 0.  0.  0.  0.]]]


 [[[ 0.  0.  0.  0.]
   [ 0.  0.  0.  0.]
   [ 0.  0.  0.  0.]]

  [[ 0.  0.  0.  0.]
   [ 0.  0.  0.  0.]
   [ 0.  0.  0.  0.]]]]


In [90]:
import numpy
N = tuple(map(int, input().split()))
array_N  = numpy.zeros(N , int)
array_M  = numpy.ones(N,int)

print(array_N)
print(array_M)

1 2 3 
[[[0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]]]


In [61]:
import numpy
N,M = (map(int, input().split()))
print( numpy.eye(N, M, k = 0))

4 3 
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]]


### Array Mathematics (Dashboard  Python  Numpy  Array Mathematics)

In [66]:
import numpy
N,M = (map(int, input().split()))


A  = numpy.zeros(shape=(N,M))
A = A.astype(int)
for i in range(N):
    A[i] = list(map(int,input().strip().split()))

B  = numpy.zeros(shape=(N,M))
B = B.astype(int)
for i in range(N):
    B[i] = list(map(int,input().strip().split()))
print(A+B)
print(A-B)
print(A*B)
print((A/B).astype(int))
print(A%B)
print(A**B)

1 4 
[[ 1.  0.  0.  0.]]
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


### Floor, Ceil and Rint

In [75]:
import numpy
my_array = numpy.array((input().split()), float)
print(numpy.floor(my_array))
print (numpy.ceil(my_array))
print (numpy.rint(my_array))


1.1  2.2  3.3  4.4  5.5  6.6  7.7  8.8  9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [ ]:
1.1  2.2  3.3  4.4  5.5  6.6  7.7  8.8  9.9

### Sum and Prod

In [80]:
import numpy
N,M = (map(int, input().split()))
A  = numpy.zeros(shape=(N,M))
A = A.astype(int)
for i in range(N):
    A[i] = list(map(int,input().strip().split()))
B=numpy.sum(A, axis = 0)
print( numpy.prod(B, axis = 0))

#print (A)

2 2
1 2
3 4
24


### Min and Max

In [81]:
import numpy
N,M = (map(int, input().split()))
A  = numpy.zeros(shape=(N,M))
A = A.astype(int)
for i in range(N):
    A[i] = list(map(int,input().strip().split()))
B=numpy.min(A, axis = 1)
print( numpy.max(B))

4 2
2 5
3 7
1 3
4 0
3


In [ ]:
4 2
2 5
3 7
1 3
4 0

### Mean, Var, and Std

In [82]:
import numpy
N,M = (map(int, input().split()))
A  = numpy.zeros(shape=(N,M))
A = A.astype(int)
for i in range(N):
    A[i] = list(map(int,input().strip().split()))
print(numpy.mean(A, axis = 1))
print( numpy.var(A, axis=0))
print(numpy.std(A))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


### Dot and Cross

In [ ]:
2
1 2
3 4
1 2
3 4

[[ 7 10]
 [15 22]]

In [89]:
import numpy
A=numpy.array(list(map(int,input().strip().split())),int)
B=numpy.array(list(map(int,input().strip().split())),int)
print(numpy.inner(A, B))
print(numpy.outer(A, B))



0 1
2 3
3
[[0 0]
 [2 3]]


### Inner and Outer 

In [ ]:
import numpy
N = int(input())


A=numpy.array([input().split() for i in range(N)],int)
B=numpy.array([input().split() for i in range(N)],int)
print(numpy.dot(A, B))

### determinents

N = int(input())
A = numpy.array([input().split() for i in range(N)], numpy.float)
print( numpy.linalg.det(A))

### Numpy Loops 

In [94]:
n = int(input())
for i in range(n):
    print(i*i)

5
0
1
4
9
16


In [100]:
import re
l = re.split('[\, \.]*',input())
for i in l : 
    print(i)


100,000,000.000
100
000
000
000


/Users/jyothi/anaconda/lib/python3.5/re.py:203: FutureWarning: split() requires a non-empty pattern match.
  return _compile(pattern, flags).split(string, maxsplit)


In [ ]:
100,000,000.000

In [115]:
import re
def email(in_put ):
    email = in_put
    match = re.search(r'[\w.-]+@[\w.-]+.\w+', email)

    if match:
        #print( "valid email :::", match.group())
        return True
    else:
        #print ("not valid:::")
        return False
email(input())

virus!@variable.:p
not valid:::


### Validating and Parsing Email Addresses

In [79]:
import email.utils
import re
N  = int(input())
l =[]
for i in range(N):
    address = input()
    li =  email.utils.parseaddr(address)
    
    e = str(li[1])
    match = re.search(r'^[a-z0-9][\w._-]+@[a-z]+\.[a-z]{1,3}$',e)
    #match = re.search(r'[a-z0-9][\w._-]+@[\w.-]+.\w+', e)
    
    #match = re.search(r'^(?!^\.)(?!.*[-_.]$)[a-zA-Z0-9]+@[a-z]+\.[a-z]{1,3}', e, re.I)
     # r'([\w.-]+)@((?:[\w]+\.)+)([a-zA-Z][2,4])'
    
    if match:
        #print(address)
        l.append(address)
for i in l:
    print(i)
       
        
    

6
shashank@9mail.com
shashank@gmail.9om
shashank@gma_il.com
shashank@mail.moc
shashank@company-mail.com
shashank@companymail.c_o
shashank@mail.moc


### Validating UID

In [ ]:
A valid UID must follow the rules below:

1.It must contain at least 2 uppercase English alphabet characters.
2.It must contain at least 3  digits (0 - 9).
3.It should only contain alphanumeric characters (a - z, A - Z & 0 -9 ).
4.No character should repeat.
5.There must be exactly 10 characters in a valid UID.

In [11]:
import re
li = []
for i in range(int(input())):
    s = input()   
    if all([re.search(r, s) for r in [r'[A-Za-z0-9]{10}',r'([A-Z].*){2}',r'([0-9].*){3}']]) and not re.search(r'.*(.).*\1', s) : 
        li.append("Valid")       
    else :
        li.append("Invalid")
for i in li : 
    print(i)

2
B1CDEF2354
B1CD102354
Valid
Invalid


### Validating Credit Card Numbers

In [ ]:
A valid credit card from ABCD Bank has the following characteristics: 

► It must start with a 4,5  or 6. 
► It must contain exactly  16 digits. 
► It must only consist of digits (0-9). 
► It may have digits in groups of 4, separated by one hyphen "-". 
► It must NOT use any other separator like ' ' , '_', etc. 
► It must NOT have 4 or more consecutive repeated digits.

Examples:

Valid Credit Card Numbers

4253625879615786
4424424424442444
5122-2368-7954-3214
Invalid Credit Card Numbers

42536258796157867       #17 digits in card number → Invalid 
4424444424442444        #Consecutive digits are repeating 4 or more times → Invalid
5122-2368-7954 - 3214   #Separators other than '-' are used → Invalid
44244x4424442444        #Contains non digit characters → Invalid
0525362587961578        #Doesn't start with 4, 5 or 6 → Invalid

In [ ]:
import re
li = []
for i in range(int(input())):
    s = input()
    
    if all([re.search(r, s) for r in [r'^[456]{16}',r'([A-Z].*){2}',r'([0-9])']]) and not re.search(r'.*(.).*\1', s) : 
        li.append("Valid")
       
    else :
        li.append("Invalid")

In [ ]:
import re

[print('Valid' if re.match(r'^[456]\d{3}(?:-?\d{4}){3}$', card) and not re.search(r'(\d)\1{3}', re.sub('-', '', card)) else 'Invalid') for card in [input() for _ in range(int(input()))]]

In [ ]:
You may do this in 2 regexes:

/^(?=.*[a-z])(?=.*[0-9])[a-z0-9]+$/i This will assure that there is at least 1 digit and 1 letter while accepting only letters and digits (no space or special characters)
/([a-z0-9])\1{2,}/i If this one is matched, then there is a repeated character. Which means you should throw false.
Explanation:

First regex:

^ : match begin of line
(?=.*[a-z]) : check if there is at least one letter
(?=.*[0-9]) : check if there is at least one digit
[a-z0-9]+ : if the checks were true, then match only digits/letters one or more times
$ : match end of line
i : modifier, match case insensitive
Second regex:

([a-z0-9]) : match and group a digit or a letter
\1{2,} : match group 1 two or more times
i : modifier, match case insensitive

In [15]:
import re
regx = re.compile(r'(?=^[456])(?!.*(\d)(?:-?\1){3,})^(?:\d{4}-?){4}$')
li = []
for i in range(int(input())):
    if bool(regx.match(input())):
        li.append("Valid")
    else :
        li.append("Invalid")
for i in li : 
    print (i)

2
4123456789123456
5133-3367-8912-3456
Valid
invalid


In [ ]:
4123456789123456
5123-4567-8912-3456
61234-567-8912-3456
4123356789123456
5133-3367-8912-3456
5123 - 3567 - 8912 - 3456

In [ ]:
import re
li = []
for i in range(int(input())):
    try:
        f = input()
        float(f)
        if bool(re.search('.[0-9]+', f)) :
            li.append("True")
        else : 
            li.append("False")
    except:
        li.append("False")
for i in li:
    print(i)

### Re.start() & Re.end()

In [68]:
import re

for i in m:
    m.end()
    
          





TypeError: '_sre.SRE_Match' object is not iterable

### Re.findall() & Re.finditer()

In [3]:
import re
from __future__ import print_function
consonents = 'QWRTYPSDFGHJKLZXCVBNM'
vowels = 'AEIOU'
match = re.findall(r'(?<=['+consonents+'])(['+vowels+']{2,})(?=['+consonents+'])', input(), flags=re.I)

if(len(match)) != 0 :
    print(*match, sep='\n')
else : 
    print('-1')

match a single character not present in the list below
-1


In [ ]:
match = re.findall(r'(?<=['+consonants+'])(['+vowels+']{2,})(?=['+consonants+'])',raw_input(),flags = re.I)

In [ ]:
match a single character not present in the list below

### Validating Roman Numerals

In [13]:
import re
regx = re.compile(r'([#]([a-fA-F0-9]{6}|[a-fA-F0-9]{3})(?=[\W]))|({)|(})',re.I)
IN = regx.match(input())
print(IN)

#FFF
None


In [15]:
a = int(input())
b = int(input())
print(a//b)
print(a/b)
    

4
3
1
1.3333333333333333


In [25]:
import xml.etree.ElementTree as etree
numlines = int(input())
XML = ''
for _ in range(numlines):
    XML += input()
    
root = etree.fromstring(XML)
sum = 0
for i in root.iter() : 
    sum = sum + (len(i.attrib))
    
print(sum)


6
<feed xml:lang='en'>
 <title>HackerRank</title>
<subtitle lang='en'>Programming challenges</subtitle>
<link rel='alternate' type='text/html' href='http://hackerrank.com/'/>
<updated>2013-12-25T12:00:00</updated>
</feed>
5


In [ ]:
<feed xml:lang='en'>
    <title>HackerRank</title>
    <subtitle lang='en'>Programming challenges</subtitle>
    <link rel='alternate' type='text/html' href='http://hackerrank.com/'/>
    <updated>2013-12-25T12:00:00</updated>
</feed>

In [26]:
import xml.etree.ElementTree as etree
def get_attr_number(node):
    # your code goes here
    sum = 0
    numlines = int(input())
    XML = ''
    for _ in range(numlines):
        XML += input()
    root = etree.fromstring(XML)
    for i in root.iter() : 
        sum = sum + (len(i.attrib))
    print(sum)

In [28]:
import xml.etree.ElementTree as etree
numlines = int(input())
XML = ''
for _ in range(numlines):
    XML += input()
tree = etree.ElementTree(etree.fromstring(XML))
root = tree.getroot()
sum = 0
for i in root.iter() : 
    sum = sum + (len(i.attrib))
print( sum)

6
<feed xml:lang='en'>
<title>HackerRank</title>
<subtitle lang='en'>Programming challenges</subtitle>
<link rel='alternate' type='text/html' href='http://hackerrank.com/'/>
<updated>2013-12-25T12:00:00</updated>
</feed>
5


In [ ]:
<feed xml:lang='en'>
    <title>HackerRank</title>
    <subtitle lang='en'>Programming challenges</subtitle>
    <link rel='alternate' type='text/html' href='http://hackerrank.com/'/>
    <updated>2013-12-25T12:00:00</updated>
</feed>

### itertools.product() 

In [30]:
from itertools import product
print (list(product([1,2,3],[3,4])))


[(1, 3), (1, 4), (2, 3), (2, 4), (3, 3), (3, 4)]


In [50]:
li1 = list(map(int, input().split()))
li2 = list(map(int, input().split()))
print (" ".join(map(str, (product(li1, li2)))))




1 2
3 4
(1, 3) (1, 4) (2, 3) (2, 4)


In [51]:
from itertools import groupby
a = input()
for key, group in groupby(a):
    print ((len(list(group)), int(key)), end=' ')
    

1222311
(1, 1) (3, 2) (1, 3) (2, 1) 

In [59]:
from itertools import groupby
in_put = input()
for k , s in groupby(in_put):
    print((len(list(s)) , int(k)),end='')

11223341
(2, 1)(2, 2)(2, 3)(1, 4)(1, 1)

### collections.Counter()

In [ ]:
from collections import Counter
n = int(input())
s = Counter(map(int,input().split()))
x = int(input())
total = []
for i in range(x):
    a,b = map(int,input().split())
    if s[a] > 0:
		total.append(b)
		s.subtract(Counter([a]))
    else:
        pass

print (sum(total))

In [ ]:
import collections

numShoes = int(raw_input())
shoes = collections.Counter(map(int, raw_input().split()))
numCust = int(raw_input())

income = 0

for i in range(numCust):
    size, price = map(int, raw_input().split())
    if shoes[size]: 
        income += price
        shoes[size] -= 1

print income

In [60]:
import collections 

numberOfShoes = int(input())

shoeSizes = collections.Counter(map(int, input().split()))
noOfCust = int(input())
sum = 0 
for i in range(noOfCust):
    size , amount = map(int, input().split())
    if(shoeSizes[size] > 0 ):
        sum = sum + amount
        shoeSizes[size] -= 1
print(sum)

10
2 3 4 5 6 8 7 6 5 18
6
6 55
6 45
6 55
4 40
18 60
10 50
200


### Calendar Module

In [ ]:
calendar.weekday(year, month, day)

In [71]:
import calendar 
dict = { 0 : 'Monday' , 1 : 'Tuesday' , 2: 'Wednesday' , 3:'Thursday' , 4:'Friday' , 5:'Saturday' , 6 :'Sunday'}
m , d , y = map(int, input().split())
week = calendar.weekday(y, m, d)
print(str(dict.get(week).upper()))


01 17 2017
TUESDAY


## Time Delta

In [72]:
import datetime as dt

a = dt.datetime(2013,12,30,23,59,59)
b = dt.datetime(2013,12,31,23,59,59)

(b-a).total_seconds()

86400.0

### Exceptions

In [13]:
li = []
for i in range(int(input())):

    try:     
        a,b  = map(int, input().split())
        li.append(a//b)
    except ZeroDivisionError as e:
        li.append("Error Code:" + e.toString()  )
        
    except ValueError as v : 
        li.append("Error Code:" +  str(v))
        
for i in li:
    print(i)


3
1 0


AttributeError: 'ZeroDivisionError' object has no attribute 'toString'

In [15]:
 li = []
for i in range(int(input())):

    try:     
        a,b  = map(int, input().split())
        print(a//b)
    except (ZeroDivisionError,ValueError) as e:
        print("Error Code:",e)

3
10
Error Code: not enough values to unpack (expected 2, got 1)
2 0
Error Code: integer division or modulo by zero
1$
Error Code: invalid literal for int() with base 10: '1$'


In [39]:
a,b  = map(int, input().split())
li=[]
tu = ()
for i in range(b):
 
   li.append(list(map(float, input().split())))

tu = zip(*li)
s =  [sum(tup) for tup in tu]
for i in s:
    print(i/b)

5 3
91 92 83 89 90.5
90 91 85 88 86
89 90 78 93 80
90.0
91.0
82.0
90.0
85.5


In [ ]:
A = [1,2,3]
B = [6,5,4]
C = [7,8,9]
X = [A] + [B] + [C]
y =  zip(*X)

s =  [sum(tup) for tup in y]
for i in s:
    print(i)

In [ ]:
zip(*[list(map(float, input().split()))

In [ ]:
5 3
89 90 78 93 80
90 91 85 88 86  
91 92 83 89 90.5

In [40]:
eval("9 + 5")

14

In [45]:
x = input()
eval(x)

print(2+4)
6


In [80]:
a,b  = map(int, input().split())
li = []
for i in  range (a):
    li.append(list(map(int , input().split())))
k = int(input())

li.sort(key=lambda x: x[k])
for i in li : 
    print()
    for x in i :
        print(x , end=" ")
    


5 3 
10 2 5 
7 1 0
9 9 9 
1 23 12
6 5 9 
1

7 1 0 
10 2 5 
6 5 9 
9 9 9 
1 23 12 

### Any or All

In [102]:
num = input()
s = num[::-1]
li = list(map(int, input().split()))
if(( all(i >= 0 for i in li)) and (int(s) == int(num))) : 
    print('True')
else :
    print ('False' )


10
1 2 3 4 5 6 7 8 9 10
False


In [85]:
original = input()   #original = number entered by user
rev = original[::-1]     #rev = reverse of original by useing scope resolution 
print ('rev of original no =',rev)
if original == rev:
    print( "no's are equal")
else:
    print ("no's are not equal")

202
rev of original no = 202
no's are equal


In [115]:
num = input()

def pal(li):
    flag = False
    for i in li:
        s = i[::-1]
        if(s== i):
            flag = True
    return flag    

strli = list(input().split())
intli = list(map(int , strli))
print(( all(i >= 0 for i in intli)) and (pal(strli))) 



3 
1 12 13
True


### ginortS

In [118]:

str_in = input()
s = sorted(str_in, key= lambda x:(x.isdigit() and int(x)%2 == 0 , x.isdigit(), x.isupper(), x.islower() ,x))

print(*(s),sep = '')

Sorting1234
ginortS1324


In [136]:
import cmath
re  = complex(input())
print(abs(re))
print(cmath.phase(complex(re.real, re.imag)))




1+2j
2.23606797749979


1.1071487177940904

In [144]:
N,M = int(input()) , int(input())
print(N//M)
print(N%M)
print (divmod(N,M))

177
10
17
7
(17, 7)


In [140]:
print(177//10)

17


In [141]:
print(177%10)

7


In [146]:
a  = int(input())
b = int(input())
m =  int(input())
print(pow(a,b))
print(pow(a,b,m))

3 
4
5 
81
1


In [ ]:
9
29
7
27

In [147]:
a  = int(input())
b = int(input())
c  = int(input())
d = int(input())
print(pow(a,b ) + pow(c,d))

9
29
7
27
4710194409608608369201743232


In [4]:
for i in range(1,int(input())): #More than 2 lines will result in 0 score. Do not leave a blank line also
    print (str(i)*(i))
    

5
1
22
333
4444


In [49]:
from itertools import combinations
st_li, m =  input().split()
j = int(m)
for k in range(j) :
    li =list(sorted(combinations(st_li,k+1)))
    for x in li:
        print ("".join(x))




HACK 2
A
C
H
K
AC
AK
CK
HA
HC
HK
